extend = "ruff_defaults.toml"

exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", "dist"]

[format]
preview = true
quote-style = "double"

[lint]
preview = true

#select = [
#    # pycodestyle
#    "E",
#    # Pyflakes
#    "F",
#    # pyupgrade
#    "UP",
#    # flake8-bugbear
#    "B",
#    # flake8-simplify
#    "SIM",
#    # isort
#    "I",
#]